version: '3'
networks:
  testapi.net:
    name: testapi_network

services:
  testapi-db:
    container_name: testapi.db
    image: postgres:11.11
    restart: always
    volumes:
      - .:/var/lib/postgresql/
      - ./create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - "5432:5432"
    networks:
      - testapi.net

  pgadmin:
    container_name: testapi.pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@test.ru"
      PGADMIN_DEFAULT_PASSWORD: "test123"
    ports:
      - "16543:80"
    depends_on:
      - testapi-db
    networks:
      - testapi.net



